### PR TITLE
fix/delete-maps

### PR DESCRIPTION
**Pull request by teye**
## Description
This pr is a fix for all delete operations on nested maps in the contract. When a map-key is deleted, the nested maps are not cleared properly, causing some leftover empty values in the contract state. 

An example is `field buff_deposit_deleg: Map ByStr20 (Map ByStr20 (Map Uint32 Uint128)` which holds the relation `deleg -> ssn -> cycle -> reward`.

An example of the map in the contract state is:
```occaml
"buff_deposit_deleg" : {
    "deleg_A_addr": {
        "ssn_A_addr": {
             "1": "10000",
        },
      "ssn_B_addr": {
             "1": "10000"
       },
    }
} 
```
In the current implementation https://github.com/Zilliqa/staking-contract/blob/main/contracts/ssnlist.scilla#L847, the reward entry is removed but the inner keys are not checked and removed.

```occaml
delete buff_deposit_deleg[deleg_A_addr][ssn_A_addr][1];
```

The above would result in the following map state:
```occaml
"buff_deposit_deleg" : {
    "deleg_A_addr": {
      "ssn_A_addr": {},  <-- empty { } left behind, clogging up contract states
      "ssn_B_addr": {
             "1": "10000"
       },
    }
} 
```
The issue with this map-key: `ssn_A_addr: {}` leftover is that scilla will match this to be a legitimate value when we check if the map has some other values:
```occaml
delete buff_deposit_deleg[deleg_A_addr][ssn_A_addr][1];
buff_deposit_map <- buff_deposit_deleg[deleg_A_addr][ssn_A_addr];
match buff_deposit_map with
| Some entry => (* { } will reach here *)
| None =>
  delete buff_deposit_deleg[deleg_A_addr][ssn_A_addr]
end
```

## Fix

There are two independent fixes.
1. Let users handle the deletion of the empty maps by incorporating additional checks when deleting key-value to also delete additional nested keys.
2. New admin transitions that takes in a list of keys to be deleted. The list of keys are computed via a **off-chain** script at https://github.com/Zilliqa/staking-tooling/tree/feat/clean-map

### Fix 1: Users Delete Fix

To remove any empty nested maps, we have to remove the "nested" keys as well, e.g.:
```occaml
delete buff_deposit_deleg[deleg_A_addr][ssn_A_addr][1];

buff_deposit_map <- buff_deposit_deleg[deleg_A_addr][ssn_A_addr];

match buff_deposit_map with
| Some entry => (* { } will reach here *)

  entry_size = builtin size entry;  <-- checked nested map length; because { } is consider as "Some" entry
  is_empty = builtin eq entry_size uint32_zero;

  match is_empty with
  | True => 
    delete buff_deposit_deleg[deleg_A_addr][ssn_A_addr]  <-- remove nested key and "{}" mapping
    // ... ...
    (* repeat the same check for buff_deposit_deleg[deleg_A_addr] to remove deleg_A_addr if there are no other ssn for this deleg *)
  | False => (* ignore *)
  end

| None => (* won't actually reach here because of { } *)
  delete buff_deposit_deleg[deleg_A_addr][ssn_A_addr]
end
```
### Affected Procedures
```
CalculateTotalWithdrawal
CalcStakeRewards
TruncateDeleg
```

### Affected Transitions
```
CompleteWithdrawal
ReDelegateStake
UpdateDeleg
WithdrawStakeRewards
WithdrawStakeAmt
```

### Fix 2: Off-chain script and Admin Transitions

1. Command is executed using the staking-tooling https://github.com/Zilliqa/staking-tooling/blob/feat/clean-map/cmd/map_purge.go.
2. The tool reads the contract state, e.g. buff_deposit_deleg and retrieves all the empty delegator keys and ssn address keys which contain empty maps
3. The keys are supplied into the transition `CleanBuffDeposit` https://github.com/Zilliqa/staking-contract/blob/fix/delete-maps/contracts/ssnlist.scilla#L1319.
4. For each of the keys in the list, do a delete from either `buff_deposit_deleg[deleg]` or `buff_deposit_deleg[deleg][ssn]` depending on what is being supplied.

### New Admin Transitions
```
CleanBuffDeposit(deleg_addr_list: List ByStr20, ssn_addr_list: List (Pair ByStr20 ByStr20), initiator: ByStr20)
CleanDirectDeposit(deleg_addr_list: List ByStr20, ssn_addr_list: List (Pair ByStr20 ByStr20), initiator: ByStr20)
CleanDelegStakePerCycle(deleg_addr_list: List ByStr20, ssn_addr_list: List (Pair ByStr20 ByStr20), initiator: ByStr20)
CleanDepositAmt(deleg_addr_list: List ByStr20, initiator: ByStr20)
CleanPendingWithdrawal(deleg_addr_list: List ByStr20, initiator: ByStr20)
CleanLastWithdrawCycle(deleg_addr_list: List ByStr20, initiator: ByStr20)
CleanLastBuffDepositCycle(deleg_addr_list: List ByStr20, initiator: ByStr20)
```

## Notes
This pr is a series of improvements as part of [ZIP-19 (WIP)](https://github.com/Zilliqa/ZIP/blob/feat/zip19/zips/zip-19.md)

### CODE REVIEW

**Comment by anton-trunov** [comment]
Do we have any estimates on how big `buff_deposit_deleg[deleg_A_addr][ssn_A_addr]` map can be? Because the command
```
buff_deposit_map <- buff_deposit_deleg[deleg_A_addr][ssn_A_addr];
```
fetches that map and if the map is big then it might cost lots of gas.

We have a case *kind of* like this documented here: https://scilla.readthedocs.io/en/latest/scilla-tips-and-tricks.html#field-map-size. Basically, to save gas one has to track the map size somewhere in the contract state.

**Comment by teye** [comment]
> Do we have any estimates on how big `buff_deposit_deleg[deleg_A_addr][ssn_A_addr]` map can be? Because the command
> 
> ```
> buff_deposit_map <- buff_deposit_deleg[deleg_A_addr][ssn_A_addr];
> ```
> 
> fetches that map and if the map is big then it might cost lots of gas.
> 
> We have a case _kind of_ like this documented here: https://scilla.readthedocs.io/en/latest/scilla-tips-and-tricks.html#field-map-size. Basically, to save gas one has to track the map size somewhere in the contract state.

@anton-trunov 
In the production contract, I am seeing up to 5 entries of `buff_deposit_deleg[deleg_A_addr][ssn_A_addr]`, i.e. something like this:
```
      "0x005e3067166a8b75d5a00c48d258d546faed7d1d": {     // deleg
          "0xb83fc2c72c44b6b869c64384375c979dc3f7cf05": {    // ssn
              "84": "16941000000000000", 
              "86": "1451109000000000",
              "87": "2500000000000000",
              "88": "1651000000000000",
              "95": "380000000000000"
          }
      },
```

I did consider the manual counting but it does not seem feasible for this use case? There are 8 maps that involves deleting of nested structure and some of them have double or triple layers. Accounting for each of the nested map size is too error-prone.

Consider the above `buff_deposit_deleg` example, we would require at least 2 other fields to manually compute the size of
`buff_deposit_deleg[deleg_A_addr]` and `buff_deposit_deleg[deleg_A_addr][ssn_A_addr]` and this is only for one delegator to one ssn.

To sidetrack a little...because at least three maps have the same nested variable types, I also have a library function to delete the maps properly (https://github.com/Zilliqa/staking-contract/blob/fix/delete-maps/contracts/ssnlist.scilla#L268). However, it uses `builtin remove`, would that consume a lot of gas too?

**Comment by bb111189** [comment]
We may need to handle more maps deletion

`deposit_amt_deleg`
example:
```
  "0x008af0cb82fe630275e12804a119bfa401265af7": {},
```

`last_buf_deposit_cycle_deleg`
```
  "0x000bd4562f12f0f0ff233908e62900fcd03a068d": {},
  "0x000e3402462768f4bf060f0b202d53aca298735e": {},
```
`last_withdraw_cycle_deleg`
```
    "0x00069fcf01e874b350dc1f64ee5c49cacc1a30ab": {},
```

**Comment by anton-trunov** [comment]
> However, it uses builtin remove, would that consume a lot of gas too since it is a copy?

@teye Yes, all the functional map operations create copies and that might be costly in terms of gas.

**Comment by anton-trunov** [comment]
@teye A minor suggestion: I think we could introduce an `is_map_empty` utility function
because I see there are several occurrences of something like
```
let map_size = builtin size map in
let is_map_empty = builtin eq map_size uint32_zero in
...
```
It's not going to reduce the amount of code because Scilla is an intermediate language but I think it's going to be a bit easier to understand the contract's logic.

**Comment by teye** [comment]
@anton-trunov, thanks for the suggestion, I think this will make the code look much cleaner.

**Comment by teye** [comment]
> Do we have any estimates on how big `buff_deposit_deleg[deleg_A_addr][ssn_A_addr]` map can be? Because the command
> 
> ```
> buff_deposit_map <- buff_deposit_deleg[deleg_A_addr][ssn_A_addr];
> ```
> 
> fetches that map and if the map is big then it might cost lots of gas.
> 
> We have a case _kind of_ like this documented here: https://scilla.readthedocs.io/en/latest/scilla-tips-and-tricks.html#field-map-size. Basically, to save gas one has to track the map size somewhere in the contract state.

I re-implemented it into an off-chain workflow and ran some tests to estimate the gas costs. However, I think we should stick with the on-chain "delete" way, (the one that is invoked by the user).

So the current off-chain workflow is:
1. Command is executed using the staking-tooling https://github.com/Zilliqa/staking-tooling/blob/feat/clean-map/cmd/map_purge.go.
2. The tool reads the contract state, e.g. buff_deposit_deleg and retrieves all the empty delegator keys and ssn address keys which contain empty maps
3. The keys are supplied into the transition `CleanBuffDeposit` https://github.com/Zilliqa/staking-contract/blob/fix/delete-maps/contracts/ssnlist.scilla#L1319.
4. For each of the keys in the list, do a delete from either `buff_deposit_deleg[deleg]` or `buff_deposit_deleg[deleg][ssn]` depending on what is being supplied.

### Gas Consumption Tests
To recap, the delete map issue can be fixed in 3 ways:
1. Off-chain; execute via the staking-tooling and supplying the keys for deletion (workflow above). As there are many ssn keys to be deleted. The staking-tooling would breakup all the keys into chunks of 100 keys per transaction. 
2. On-chain; execute a transition to use `builtin remove` to clear the keys properly, 
3. On-chain execute a transition to use `delete map[key_1][key_2]` with additional checks to to delete outer-most keys if inner map is empty.

**Test methodology**
 - A subset of the contract state is migrated from production into the isolated server for testing.
 - For the off-chain method, the staking-tooling is executed.
 - For both of the on-chain method, after the migration, a deleg and ssn is chosen to fulfill this nested scenario:
 ```
 buff_deposit_deleg:
     deleg:
        ssn:
           "1": "XXXX",
           "2": "XXXX",
           "3": "XXXX",
           "4": "XXXX",
      ...
     // other deleg
 ``` 

The gas costs on `buff_deposit_deleg`, a triple nested map is as follows:
| | Off-chain Staking-tooling | On-chain "user-self" invoked "remove"  | On-chain "user-self" invoked "delete"
| ----- | --------- | ------- | ------- |
| No. of deleg keys | ~300 | ~304 | ~1563 |
| No. of empty keys REMOVED | 155 deleg keys<br>165 ssn keys | 1 key | 1 key |
| Gas Price (ZIL) | 0.002 | 0.002 | 0.002 |
| Gas Limit | 20000 | 10000 | 10000 |
| Txn Fee (ZIL) | [c426dd54b95551cb7a78a7903b38eef2603d13e4e8685b26c065c738f824bdf0](https://devex.zilliqa.com/tx/c426dd54b95551cb7a78a7903b38eef2603d13e4e8685b26c065c738f824bdf0?network=https%3A%2F%2Fzilliqa-isolated-server.zilliqa.com) **14.2** (Remove ALL inner ssn) [703da73e42a22d0263e11646ac20e9f06e21cccb1eb90a6c228fc5af53bb7736](https://devex.zilliqa.com/tx/703da73e42a22d0263e11646ac20e9f06e21cccb1eb90a6c228fc5af53bb7736?network=https%3A%2F%2Fzilliqa-isolated-server.zilliqa.com) **14.2** (Remove ALL inner ssn) [f6b9daedaa7e30691dd0f6c2d5dc676bbe4108a017d7a0c8630bee8f6f6a15f4](https://devex.zilliqa.com/tx/f6b9daedaa7e30691dd0f6c2d5dc676bbe4108a017d7a0c8630bee8f6f6a15f4?network=https%3A%2F%2Fzilliqa-isolated-server.zilliqa.com) **4.98** (Remove ALL outer deleg) [bc7785803daeda1545b184192a5dee51207a801868990a81917e43b2c06ad397](https://devex.zilliqa.com/tx/bc7785803daeda1545b184192a5dee51207a801868990a81917e43b2c06ad397?network=https%3A%2F%2Fzilliqa-isolated-server.zilliqa.com) **4.98** (Remove ALL outer deleg) | [d37a45cb4105030fd380a94b15b15ce130a793d92dc2f285fc79b2407edc6f5c](https://devex.zilliqa.com/tx/d37a45cb4105030fd380a94b15b15ce130a793d92dc2f285fc79b2407edc6f5c?network=https%3A%2F%2Fzilliqa-isolated-server.zilliqa.com) **11.6** | [9b325d3a49e809332360c68ad44db748e597d174af4286c9dccea4fc5abac2be](https://devex.zilliqa.com/tx/9b325d3a49e809332360c68ad44db748e597d174af4286c9dccea4fc5abac2be?network=https%3A%2F%2Fzilliqa-isolated-server.zilliqa.com) **0.87** |

From the above results, we can let the user delete the keys themselves as it is cheaper and less complicated. A map with ~1500 keys with each of them having at least 1 inner map, only cost about 0.87 ZIL. Hence `copy <- buff_deposit_deleg[deleg]` or `copy2 <- buff_deposit_deleg[deleg][ssn]` would not incur a lot of gas. 

Instead, the **off-chain** method would result in more gas being consumed because of the for loops. In the above example, it costs 14.2 ZIL to clean 100 inner keys. Currently, the production has 19000 empty inner keys, this amounts to 2698 ZIL (190 * 14.2) to be forked out by the admin.

**Comment by teye** [comment]
An update on the gas consumption.

I ran `WithdrawStakeRewards` as it will invoked `CalcStakeRewards` and contains three delete statements that covers the largest nested maps in the contract state. https://github.com/Zilliqa/staking-contract/blob/fix/delete-maps/contracts/ssnlist.scilla#L881

**Withdraw Stake Rewards (Original)**
- [0xd14b0f962774b042f34e3e85019b4f46942a8d779218a2f33e0ab160f2346c4a](https://devex.zilliqa.com/tx/d14b0f962774b042f34e3e85019b4f46942a8d779218a2f33e0ab160f2346c4a?network=https%3A%2F%2Fzilliqa-isolated-server.zilliqa.com)
- Txn fee: **1.986**

**Withdraw Stake Rewards (Proper Delete Fix)**
- [0x5168ee32e3fae2a5ca3ccaefee88ff04b97228c14f0c01ceaafa69dcc41e899c](https://devex.zilliqa.com/tx/5168ee32e3fae2a5ca3ccaefee88ff04b97228c14f0c01ceaafa69dcc41e899c?network=https%3A%2F%2Fzilliqa-isolated-server.zilliqa.com)
- Txn fee: **2.01**

**Withdraw Stake Rewards (Delete Fix, Maps containing 1000 keys)**
- [2f52531a8cd8aba5ef269561346836a9deffc864175a541d2970fa57ecaeb69a](https://devex.zilliqa.com/tx/2f52531a8cd8aba5ef269561346836a9deffc864175a541d2970fa57ecaeb69a?network=https%3A%2F%2Fzilliqa-isolated-server.zilliqa.com)
- Txn fee: **2.01**

### Observation
Thus, it can be observed that with the simple delete fix, the increase in txn fee is minimal to the user; around **1-2%**. The only "con" is that more code is required to properly delete.

Here is an example of deleting the `buff_deposit_deleg` properly:
```occaml
procedure ProperDeleteBuffDeposit(deleg: ByStr20, ssnaddr: ByStr20, cycle: Uint32)
  delete buff_deposit_deleg[deleg][ssnaddr][cycle];
  deleg_ssn_map <- buff_deposit_deleg[deleg][ssnaddr];
  match deleg_ssn_map with
  | Some deleg_ssn_entry =>
    is_inner_map_empty = is_cycle_reward_map_empty deleg_ssn_entry;
    match is_inner_map_empty with
    | True =>
      delete buff_deposit_deleg[deleg][ssnaddr];
      deleg_map <- buff_deposit_deleg[deleg];
      match deleg_map with
      | Some deleg_entry =>
        is_outer_map_empty = is_ssn_cycle_reward_map_empty deleg_entry;
        match is_outer_map_empty with
        | True =>
          delete buff_deposit_deleg[deleg]
        | False =>
        end
      | None => delete buff_deposit_deleg[deleg]
      end
    | False =>
    end
  | None =>
    delete buff_deposit_deleg[deleg][ssnaddr]
  end
end
```
I think we can fix the delete in the code instead of calling on-chain script. We can leave the on-chain portion perhaps for the migration process.

**Comment by bb111189** [comment]
> code



> An update on the gas consumption.
> 
> I ran `WithdrawStakeRewards` as it will invoked `CalcStakeRewards` and contains three delete statements that covers the largest nested maps in the contract state. https://github.com/Zilliqa/staking-contract/blob/fix/delete-maps/contracts/ssnlist.scilla#L881
> 
> **Withdraw Stake Rewards (Original)**
> 
> * [0xd14b0f962774b042f34e3e85019b4f46942a8d779218a2f33e0ab160f2346c4a](https://devex.zilliqa.com/tx/d14b0f962774b042f34e3e85019b4f46942a8d779218a2f33e0ab160f2346c4a?network=https%3A%2F%2Fzilliqa-isolated-server.zilliqa.com)
> * Txn fee: **1.986**
> 
> **Withdraw Stake Rewards (Proper Delete Fix)**
> 
> * [0x5168ee32e3fae2a5ca3ccaefee88ff04b97228c14f0c01ceaafa69dcc41e899c](https://devex.zilliqa.com/tx/5168ee32e3fae2a5ca3ccaefee88ff04b97228c14f0c01ceaafa69dcc41e899c?network=https%3A%2F%2Fzilliqa-isolated-server.zilliqa.com)
> * Txn fee: **2.01**
> 
> **Withdraw Stake Rewards (Delete Fix, Maps containing 1000 keys)**
> 
> * [2f52531a8cd8aba5ef269561346836a9deffc864175a541d2970fa57ecaeb69a](https://devex.zilliqa.com/tx/2f52531a8cd8aba5ef269561346836a9deffc864175a541d2970fa57ecaeb69a?network=https%3A%2F%2Fzilliqa-isolated-server.zilliqa.com)
> * Txn fee: **2.01**
> 
> **Withdraw Stake Rewards (Delete Fix, Delegator stake with 10 ssn)**
> 
> * [0a943d45861444a96d427bc80a921d557319be1503003d9b3f10789621d76ead](https://devex.zilliqa.com/tx/0a943d45861444a96d427bc80a921d557319be1503003d9b3f10789621d76ead?network=https%3A%2F%2Fzilliqa-isolated-server.zilliqa.com)
> * Txn fee: **2.1**
> 
> ### Observation
> With the delete fix, the maps are properly cleared and the increase in txn fee is minimal to the user; around **1-2%**. The only "con" is that more code is required to properly delete.
> 
> Here is an example of deleting the `buff_deposit_deleg` properly:
> 
> ```
> procedure ProperDeleteBuffDeposit(deleg: ByStr20, ssnaddr: ByStr20, cycle: Uint32)
>   delete buff_deposit_deleg[deleg][ssnaddr][cycle];
>   deleg_ssn_map <- buff_deposit_deleg[deleg][ssnaddr];
>   match deleg_ssn_map with
>   | Some deleg_ssn_entry =>
>     is_inner_map_empty = is_cycle_reward_map_empty deleg_ssn_entry;
>     match is_inner_map_empty with
>     | True =>
>       delete buff_deposit_deleg[deleg][ssnaddr];
>       deleg_map <- buff_deposit_deleg[deleg];
>       match deleg_map with
>       | Some deleg_entry =>
>         is_outer_map_empty = is_ssn_cycle_reward_map_empty deleg_entry;
>         match is_outer_map_empty with
>         | True =>
>           delete buff_deposit_deleg[deleg]
>         | False =>
>         end
>       | None => delete buff_deposit_deleg[deleg]
>       end
>     | False =>
>     end
>   | None =>
>     delete buff_deposit_deleg[deleg][ssnaddr]
>   end
> end
> ```
> 
> I think we can fix the delete in the code instead of calling the on-chain script. We can leave the on-chain portion perhaps for the migration process.

yes I agreed. Very nice work on testing out both approaches.

**Comment by bb111189** [comment]
@anton-trunov  seems like the gas impact to the user is not very significant. I think the clean-up can be done by the user automatically when the withdrawal operation is invoked.

**Review by bb111189 — APPROVED** [review]

**Review by renlulu — APPROVED** [review]

**Pull request merged**
