### PR TITLE
Scilla GitHub action to test contracts

### PR DESCRIPTION
**Pull request by anton-trunov**
Right now this just typechecks the four existing contracts. And adds a badge to the README file indicating the status of the recently run action.

### CODE REVIEW

**Comment by anton-trunov** [comment]
Folks, CI shows that typechecking `contracts/multisig_wallet.scilla` fails with the following errors:
```
contracts/multisig_wallet.scilla:211:9: error: Constructor AddSSN expects 6 type arguments, but got 7.
contracts/multisig_wallet.scilla:727:14: error: Couldn't resolve the identifier "custom_transaction_msg_as_list". 
contracts/multisig_wallet.scilla:758:11: error: Procedure ExecuteCustomTransaction not found.
```

**Comment by bb111189** [comment]
This is awesome! @anton-trunov

**Review by bb111189 — APPROVED** [review]

**Comment by anton-trunov** [comment]
Thanks @bb111189!

Please don't merge yet, let me try to make CI typecheck all the contracts even if it fails on some of them.

**Comment by bb111189** [comment]
Sure.

**Comment by anton-trunov** [comment]
@bb111189 Ok, it's ready. The result is here: https://github.com/Zilliqa/staking-contract/pull/83/checks?check_run_id=1061152117.

I opened two issues uncovered by CI: #84 and #85.

Once the issues are fixed the subsequent PRs will be checked much faster because caching does not kick in on failed builds. Without caching it takes around 15 minutes to install everything, compile Scilla and run the tests. With caching the build time reduces to around 2 mins.

**Comment by bb111189** [comment]
Rebased this branch to the latest `dev` branch. Let's see the checks again

**Comment by anton-trunov** [comment]
multisig has been fixed, but ssnlist is still failing

**Pull request merged**
